<a href="https://colab.research.google.com/github/anwarbabukm/DeepLearning/blob/main/Customer_Churn_For_Bank.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
from google.colab import files
uploaded = files.upload()


Saving Customer_Churn_Modelling.csv to Customer_Churn_Modelling.csv


In [5]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Flatten, Dense

In [6]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

In [8]:
import io
dataset = pd.read_csv(io.BytesIO(uploaded['Customer_Churn_Modelling.csv']))

In [9]:
dataset.head()

RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [10]:
X = dataset.drop(labels=['CustomerId', 'Surname', 'RowNumber', 'Exited'], axis = 1)
y = dataset['Exited']

In [11]:
X.head()

CreditScore Geography  Gender  ...  HasCrCard  IsActiveMember  EstimatedSalary
0          619    France  Female  ...          1               1        101348.88
1          608     Spain  Female  ...          0               1        112542.58
2          502    France  Female  ...          1               0        113931.57
3          699    France  Female  ...          0               0         93826.63
4          850     Spain  Female  ...          1               1         79084.10

[5 rows x 10 columns]

In [12]:
y.head()

0    1
1    0
2    1
3    0
4    0
Name: Exited, dtype: int64

In [13]:
from sklearn.preprocessing import LabelEncoder

In [14]:
label1 = LabelEncoder()
X['Geography'] = label1.fit_transform(X['Geography'])
label = LabelEncoder()
X['Gender'] = label.fit_transform(X['Gender'])
X.head()

CreditScore  Geography  Gender  ...  HasCrCard  IsActiveMember  EstimatedSalary
0          619          0       0  ...          1               1        101348.88
1          608          2       0  ...          0               1        112542.58
2          502          0       0  ...          1               0        113931.57
3          699          0       0  ...          0               0         93826.63
4          850          2       0  ...          1               1         79084.10

[5 rows x 10 columns]

In [15]:
X = pd.get_dummies(X, drop_first=True, columns=['Geography'])
X.head()

CreditScore  Gender  Age  ...  EstimatedSalary  Geography_1  Geography_2
0          619       0   42  ...        101348.88            0            0
1          608       0   41  ...        112542.58            0            1
2          502       0   42  ...        113931.57            0            0
3          699       0   39  ...         93826.63            0            0
4          850       0   43  ...         79084.10            0            1

[5 rows x 11 columns]

In [16]:
from sklearn.preprocessing import StandardScaler

In [17]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0, stratify = y)

In [18]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [19]:
X_train

array([[-1.24021723, -1.09665089,  0.77986083, ...,  1.64099027,
        -0.57812007, -0.57504086],
       [ 0.75974873,  0.91186722, -0.27382717, ..., -1.55587522,
         1.72974448, -0.57504086],
       [-1.72725557, -1.09665089, -0.9443559 , ...,  1.1038111 ,
        -0.57812007, -0.57504086],
       ...,
       [-0.51484098,  0.91186722,  0.87565065, ..., -1.01507508,
         1.72974448, -0.57504086],
       [ 0.73902369, -1.09665089, -0.36961699, ..., -1.47887193,
        -0.57812007, -0.57504086],
       [ 0.95663657,  0.91186722, -1.32751517, ...,  0.50945854,
        -0.57812007,  1.73900686]])

# ***Building ANN Model***

In [20]:
model = Sequential()
model.add(Dense(X.shape[1], activation='relu', input_dim = X.shape[1]))
model.add(Dense(128, activation='relu'))
model.add(Dense(1, activation = 'sigmoid'))

In [21]:
model.compile(optimizer='adam', loss = 'binary_crossentropy', metrics=['accuracy'])

In [22]:
model.fit(X_train, y_train.to_numpy(), batch_size = 10, epochs = 10, verbose = 1)

Epoch 1/10
800/800 [==============================] - 1s 972us/step - loss: 0.4519 - accuracy: 0.8015
Epoch 2/10
800/800 [==============================] - 1s 1ms/step - loss: 0.4111 - accuracy: 0.8185
Epoch 3/10
800/800 [==============================] - 1s 962us/step - loss: 0.3755 - accuracy: 0.8445
Epoch 4/10
800/800 [==============================] - 1s 976us/step - loss: 0.3554 - accuracy: 0.8549
Epoch 5/10
800/800 [==============================] - 1s 1ms/step - loss: 0.3478 - accuracy: 0.8579
Epoch 6/10
800/800 [==============================] - 1s 992us/step - loss: 0.3430 - accuracy: 0.8597
Epoch 7/10
800/800 [==============================] - 1s 932us/step - loss: 0.3396 - accuracy: 0.8605
Epoch 8/10
800/800 [==============================] - 1s 952us/step - loss: 0.3360 - accuracy: 0.8609
Epoch 9/10
800/800 [==============================] - 1s 975us/step - loss: 0.3356 - accuracy: 0.8606
Epoch 10/10
800/800 [==============================] - 1s 972us/step - loss: 0.3329 - 

In [23]:
y_pred = model.predict_classes(X_test)

Instructions for updating:
Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).


In [24]:
y_pred

array([[0],
       [0],
       [0],
       ...,
       [0],
       [1],
       [0]], dtype=int32)

In [25]:
model.evaluate(X_test, y_test.to_numpy())

63/63 [==============================] - 0s 721us/step - loss: 0.3535 - accuracy: 0.8570


[0.35349521040916443, 0.8569999933242798]

In [26]:
from sklearn.metrics import confusion_matrix, accuracy_score

In [27]:
confusion_matrix(y_test, y_pred)

array([[1541,   52],
       [ 234,  173]])

In [28]:
accuracy_score(y_test, y_pred)

0.857